version: 3.9 
services:

  webserver:
    container_name: nginx_server 
    image: nginx:latest 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - news_classification_network 
    ports:
      - "8080:80"
    depends_on:
      - application
  
  application:
    container_name: application_service 
    build: ../
    env_file:
      - ./env/env_file.env 
    networks: 
      - news_classification_network

  postgresql:
    container_name: postgres_container
    image: postgres:latest 
    env_file: 
      - ../env/proj_env.env 
      - ../env/database_env.env
    ports:
      - "5432:5432"
    networks:
      - news_classification_network 
    
