apiVersion: v1 
kind: Service 
metadata:
  name: news-service 
  namespace: ml-namespace
spec:
  labels:
    app: news-app 
  ports:
    - name: http 
      containerPort: 8000
      port: 8080

--- 

apiVersion: v1
kind: Deployment 
metadata:
  name: news-app
  namespace: ml-namespace
spec:
  template:
    metadata:
      labels:
        app: news-app
    spec:
      containers:
        - name: news-app 
          image: crazycoderrr/news_ml_application:latest 
          ports:
            - name: http 
              containerPort: 8080
              targetPort: 8080
              protocol: TCP 
          imagePullPolicy: IfNotPresent
          terminationGracePeriodSeconds: 60 
          envFrom:
            configMapRef:
              - name: news-application-map 
          