apiVersion: v1
kind: ConfigMap 
metadata:
  name: news-application-map
  namespace: ml-namespace
stringData:
  APPLICATION_HOST: "localhost"
  APPLICATION_PORT: "8080"
---
apiVersion: v1
kind: Secret 
metadata:
  name: db-application-map
  namespace: ml-namespace
data:
  DATABASE_HOST: "postgresql"
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres_user"
  DATABASE_PASSWORD: "postgres_password"
